# Generated by Django 4.2.28 on 2026-02-14 18:01

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=50, unique=True)),
                ('destination', models.CharField(choices=[('KAMPALA', 'Kampala'), ('NAIROBI', 'Nairobi'), ('GOMA', 'Goma')], max_length=20)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_nid', models.CharField(max_length=16)),
                ('receiver_name', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=20)),
                ('customs_cleared', models.BooleanField(default=False)),
                ('tax_id', core.fields.EncryptedTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
